package com.techjagannath.digital_identification.facade.registercard;

import com.techjagannath.digital_identification.models.registerCards.kidsProfile.RegisterCardUserKidsDetailsRequestModel;
import com.techjagannath.digital_identification.models.registerCards.kidsProfile.RegisterCardUserKidsDetailsResultModel;

public interface RegisterCardDetailsFacade {
    RegisterCardUserKidsDetailsResultModel facadeEntryPointForRegisterCardUserKidsDetails(RegisterCardUserKidsDetailsRequestModel requestModel);
}
