spring.application.name=digital-identification

# ================= DATABASE =================
#spring.datasource.url=jdbc:sqlserver://localhost:1434;databaseName=digital_identification;encrypt=false
#spring.datasource.username=sa
#spring.datasource.password=Admin@123

## production
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

# ================= JPA =================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false