package com.techjagannath.digital_identification.facade.usermanagement;

import com.techjagannath.digital_identification.models.usermanagement.RegisterUserRequestModel;
import com.techjagannath.digital_identification.models.usermanagement.RegisterUserResultModel;
import com.techjagannath.digital_identification.models.usermanagement.businessProfile.RegisterCardUserBusinessDetailsRequestModel;
import com.techjagannath.digital_identification.models.usermanagement.businessProfile.RegisterCardUserBusinessDetailsResultModel;
import com.techjagannath.digital_identification.models.usermanagement.petsProfile.RegisterCardUserPetsDetailsRequestModel;
import com.techjagannath.digital_identification.models.usermanagement.petsProfile.RegisterCardUserPetsDetailsResultModel;
import com.techjagannath.digital_identification.models.usermanagement.saveChildProfileDetals.SaveUserChildProfileDetailsRequestModel;
import com.techjagannath.digital_identification.models.usermanagement.saveChildProfileDetals.SaveUserChildProfileDetailsResultModel;
import com.techjagannath.digital_identification.models.usermanagement.seniorProfile.RegisterCardUserSeniorDetailsRequestModel;
import com.techjagannath.digital_identification.models.usermanagement.seniorProfile.RegisterCardUserSeniorDetailsResultModel;
import com.techjagannath.digital_identification.models.usermanagement.socialProfile.RegisterCardUserSocialDetailsRequestModel;
import com.techjagannath.digital_identification.models.usermanagement.socialProfile.RegisterCardUserSocialDetailsResultModel;
import com.techjagannath.digital_identification.models.usermanagement.vehicleProfile.RegisterCardUserVehicleDetailsRequestModel;
import com.techjagannath.digital_identification.models.usermanagement.vehicleProfile.RegisterCardUserVehicleDetailsResultModel;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.validation.Valid;

public interface UserManagementFacade {

    RegisterUserResultModel facadeEntryPointForRegisterUser(RegisterUserRequestModel requestModel);

    SaveUserChildProfileDetailsResultModel facadeEntryPointForSaveUserChildProfileDetails(HttpServletRequest request, SaveUserChildProfileDetailsRequestModel requestModel);

    RegisterCardUserSeniorDetailsResultModel facadeEntryPointForSaveUserSeniorProfileDetails(HttpServletRequest request, @Valid RegisterCardUserSeniorDetailsRequestModel requestModel);

    RegisterCardUserBusinessDetailsResultModel facadeEntryPointForSaveUserBusinessProfileDetails(HttpServletRequest request, @Valid RegisterCardUserBusinessDetailsRequestModel requestModel);

    RegisterCardUserVehicleDetailsResultModel facadeEntryPointForSaveUserVehicleProfileDetails(HttpServletRequest request, @Valid RegisterCardUserVehicleDetailsRequestModel requestModel);

    RegisterCardUserPetsDetailsResultModel facadeEntryPointForSaveUserPetsProfileDetails(HttpServletRequest request, @Valid RegisterCardUserPetsDetailsRequestModel requestModel);

    RegisterCardUserSocialDetailsResultModel facadeEntryPointForSaveUserSocialProfileDetails(HttpServletRequest request, @Valid RegisterCardUserSocialDetailsRequestModel requestModel);
}
