package com.techjagannath.digitalidentification.service.teacher;

import com.techjagannath.digitalidentification.models.student.verifyuid.VerifyNfcUidResultModel;
import com.techjagannath.digitalidentification.models.teacher.addhomework.TeacherAddHomeworkRequestModel;
import com.techjagannath.digitalidentification.models.teacher.addhomework.TeacherAddHomeworkResultModel;
import com.techjagannath.digitalidentification.models.teacher.homepage.inforcard.RetrieveTeacherHomePageInfoCardDetailsResultModel;
import com.techjagannath.digitalidentification.models.teacher.homepage.reviewrequestupdatestatus.RetrieveTeacherHomeworkReviewRequestUpdateStatusRequestModel;
import com.techjagannath.digitalidentification.models.teacher.homepage.reviewrequestupdatestatus.RetrieveTeacherHomeworkReviewRequestUpdateStatusResultModel;
import com.techjagannath.digitalidentification.models.teacher.homepage.revivewrequest.RetrieveTeacherHomeworkReviewRequestDetailsResultModel;
import com.techjagannath.digitalidentification.models.teacher.homeworkpage.overviewcards.RetrieveTeacherHomeworkOverviewCardsResultModel;
import com.techjagannath.digitalidentification.models.teacher.register.RegisterTeacherUidRequestModel;
import com.techjagannath.digitalidentification.models.teacher.register.RegisterTeacherUidResultModel;
import jakarta.servlet.http.HttpServletRequest;

import java.util.List;

public interface TeacherService {

    VerifyNfcUidResultModel serviceEntryPointForVerifyTeacherNfcUid(String uid);

    RegisterTeacherUidResultModel serviceEntryPointForRegisterTeacherNfcUid(String uid, RegisterTeacherUidRequestModel requestModel);

    TeacherAddHomeworkResultModel serviceEntryPointForAddHomework(HttpServletRequest request, TeacherAddHomeworkRequestModel requestModel);

    RetrieveTeacherHomePageInfoCardDetailsResultModel serviceEntryPointForRetrieveHomePageInfoCardDetails(HttpServletRequest request);

    RetrieveTeacherHomeworkOverviewCardsResultModel serviceEntryPointForHomeworkPageOverview(HttpServletRequest request);

    List<RetrieveTeacherHomeworkReviewRequestDetailsResultModel> serviceEntryPointForHomeworkReviewRequestDetails(HttpServletRequest request);

    RetrieveTeacherHomeworkReviewRequestUpdateStatusResultModel serviceEntryPointForReviewRequestUpdateStatus(HttpServletRequest request, RetrieveTeacherHomeworkReviewRequestUpdateStatusRequestModel requestModel);
}
