package com.techjagannath.digitalidentification.facade.teacher;

import com.techjagannath.digitalidentification.models.student.notice.table.GetNoticePageTableDataResultModel;
import com.techjagannath.digitalidentification.models.student.verifyuid.VerifyNfcUidResultModel;
import com.techjagannath.digitalidentification.models.teacher.addhomework.TeacherAddHomeworkRequestModel;
import com.techjagannath.digitalidentification.models.teacher.addhomework.TeacherAddHomeworkResultModel;
import com.techjagannath.digitalidentification.models.teacher.homepage.inforcard.RetrieveTeacherHomePageInfoCardDetailsResultModel;
import com.techjagannath.digitalidentification.models.teacher.homepage.reviewrequestupdatestatus.RetrieveTeacherHomeworkReviewRequestUpdateStatusRequestModel;
import com.techjagannath.digitalidentification.models.teacher.homepage.reviewrequestupdatestatus.RetrieveTeacherHomeworkReviewRequestUpdateStatusResultModel;
import com.techjagannath.digitalidentification.models.teacher.homepage.revivewrequest.RetrieveTeacherHomeworkReviewRequestDetailsResultModel;
import com.techjagannath.digitalidentification.models.teacher.homeworkpage.overviewcards.RetrieveTeacherHomeworkOverviewCardsResultModel;
import com.techjagannath.digitalidentification.models.teacher.register.RegisterTeacherUidRequestModel;
import com.techjagannath.digitalidentification.models.teacher.register.RegisterTeacherUidResultModel;
import jakarta.servlet.http.HttpServletRequest;
import org.springframework.web.multipart.MultipartFile;

import java.util.List;

public interface TeacherFacade {

    VerifyNfcUidResultModel facadeEntryPointForVerifyTeacherNfcUid(String uid);

    RegisterTeacherUidResultModel facadeEntryPointForRegisterTeacherNfcUid(String uid, RegisterTeacherUidRequestModel requestModel);

    TeacherAddHomeworkResultModel facadeEntryPointForAddHomework(HttpServletRequest request, TeacherAddHomeworkRequestModel requestModel, List<MultipartFile> files);

    RetrieveTeacherHomePageInfoCardDetailsResultModel facadeEntryPointForRetrieveHomePageInfoCardDetails(HttpServletRequest request);

    RetrieveTeacherHomeworkOverviewCardsResultModel facadeEntryPointForHomeworkPageOverviewCards(HttpServletRequest request);

    List<RetrieveTeacherHomeworkReviewRequestDetailsResultModel> facadeEntryPointForHomeworkReviewRequestDetails(HttpServletRequest request);

    RetrieveTeacherHomeworkReviewRequestUpdateStatusResultModel facadeEntryPointForHomeworkReviewRequestUpdateStatus(HttpServletRequest request, RetrieveTeacherHomeworkReviewRequestUpdateStatusRequestModel requestModel);

    List<GetNoticePageTableDataResultModel> facadeEntryPointForRetrieveNoticePageTable(HttpServletRequest request);
}
